<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOgxt5XO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOgxt5XO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOgxt5XO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOgxt5XO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOgxt5XO\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ogxt5XO',
    'container.build_id' => '93dc10af',
    'container.build_time' => 1625833907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOgxt5XO');
