<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7xoLduS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7xoLduS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7xoLduS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7xoLduS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7xoLduS\App_KernelDevDebugContainer([
    'container.build_hash' => '7xoLduS',
    'container.build_id' => 'a197cfaf',
    'container.build_time' => 1617311252,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7xoLduS');
